Online_Market/djmarketplace/app_shops/urls.py
from django.urls import path
from app_shops.views import Main, Goods, BestSellingItemView

urlpatterns = [
    path('', Main.as_view(), name='main'),
    path('<int:pk>/goods', Goods.as_view(), name='goods'),
    path('/best_item', BestSellingItemView.as_view(), name='best_item')
]

Online_Market/djmarketplace/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(r'^$', views.cart_detail, name='cart_detail'),
    path(r'^add/<int:product_id>/$', views.cart_add, name='cart_add'),
    path(r'^remove/<int:product_id>/$', views.cart_remove, name='cart_remove'),
]

Online_Market/djmarketplace/djmarketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'cart/', include('cart.urls')),
    path('', include('app_shops.urls')),
    path('profile/', include('app_users.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Online_Market/djmarketplace/app_shops/models.py
from django.db import models
from django.shortcuts import reverse


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=150, unique=True, verbose_name='Title')

    class Meta:
        verbose_name_plural = 'Category'
        verbose_name = 'Category'
        ordering = ('title',)

    def __str__(self):
        return self.title


class Shop(models.Model):
    title = models.CharField(max_length=150, unique=True, verbose_name='Title')
    category = models.ManyToManyField(Category)

    class Meta:
        verbose_name_plural = 'Shops'
        verbose_name = 'Shop'
        ordering = ('title',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('goods', args=[str(self.pk)])


class Good(models.Model):
    title = models.CharField(max_length=150, unique=True, verbose_name='Title')
    description = models.CharField(max_length=150, blank=True, verbose_name='Description')
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Price')
    quantity = models.PositiveIntegerField()
    bought = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Goods'
        verbose_name = 'Good'
        ordering = ('title',)

    def __str__(self):
        return self.title

Online_Market/djmarketplace/app_shops/forms.py
from django import forms


class DateForm(forms.Form):
    date = forms.DateField(input_formats=['%d/%m/%Y'], help_text='day/mouth/year')


class QuantityForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, label='Quantity')

Online_Market/djmarketplace/app_shops/views.py
from django.db.models import Sum
from django.views.generic import ListView, DetailView, FormView

from app_shops.forms import DateForm
from cart.forms import CartAddProductForm
from app_shops.models import Shop, Good


class Main(ListView):
    template_name = 'app_shop/main.html'
    context_object_name = 'shops'

    def get_queryset(self):
        queryset = Shop.objects.prefetch_related('category')
        return queryset


class Goods(DetailView, FormView):
    model = Shop
    template_name = 'app_shop/goods.html'
    context_object_name = 'shops'
    success_url = 'goods'
    form_class = CartAddProductForm


class BestSellingItemView(FormView, ListView):
    template_name = 'app_shop/best_selling_item.html'
    form_class = DateForm
    context_object_name = 'order'

    def get_queryset(self):
        if self.request.GET:
            form_date = self.form_class(self.request.GET)
            if form_date.is_valid():
                date = form_date.cleaned_data['date']
                queryset = Good.objects.filter(
                    order__created_at__gte=date
                ).annotate(quantity_sum=Sum('order__quantity')).order_by(
                    '-quantity_sum')[:8]
                return queryset

Online_Market/djmarketplace/app_shops/templates/app_shop/basket.html
{% extends 'base.html' %}


{% block title %} Basket
        {% endblock %}

{% block body %}

<h2>Basket</h2><br>
    {% if  basket %}
        {% for b in basket %}
            {{ b.good.title }}: {{ b.quantity }} * {{ b.good.price }} = {{ sum_good }} <br>
        {% endfor %}
    {% else %}
        Cart is empty
    {% endif %}



{% endblock %}

Online_Market/djmarketplace/app_shops/templates/app_shop/best_selling_item.html
{% extends 'base.html' %}

{% block title %}  {{ shops.title }}
        {% endblock %}

{% block body %}
    <form method="get">
        {% csrf_token %}

        {{ form.date }}

        <button type="submit">Search</button>
    </form>
    {% if order %}
    Top 10 Products<br>
    {% for item in order %}
        {{ item.title }} : Bought: {{ item.quantity_sum }}<br>
    {% endfor %}
    {% else %}
    There were no orders
    {% endif %}
{% endblock %}

Online_Market/djmarketplace/app_shops/templates/app_shop/goods.html
{% extends 'base.html' %}

{% block title %} Goods {{ shops.title }}
        {% endblock %}

{% block body %}
<h1>All Goods </h1><br>
        {% if shops %}
            {% for s in shops.good_set.all %}
                <li> <b>{{ s.title }}</b><br>
                 <p class="price">${{ s.price }}</p>
                    <form action="{% url "cart_add" s.id %}" method="post">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <input type="submit" value="Add to cart">
                </form>
                </li>

            {% endfor %}
        {% else %}
        <p>No goods</p>
        {% endif %}
{% endblock %}

Online_Market/djmarketplace/app_shops/templates/app_shop/main.html
{% extends 'base.html' %}


{% block title %} Main
        {% endblock %}

{% block body %}
<h1>All Shops </h1><br>
        {% if shops %}
        <ul>
            {% for s in shops %}
            <li><b>{{ s.title }} |
                Category:
                {% for c in s.category.all %}
                {{ c.title }}
                {% endfor %}</b><br>
                {{ s.description|truncatewords:15 }}
                <br><a href="{% url   'goods' s.pk %}"><button> More </button></a><br><br>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>No shops</p>
        {% endif %}
{% endblock %}